move monster_* monster/
move flag_* flag/
move house_* house/
move ufo_* ufo/
move man_* man/
move car_* car/
move coin_* coin/
move sword_* sword/
move pencil_* pencil/
move pistol_* pistol/
move rifle_* rifle/